config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  scope '(:locale)', locale: /fr|en/ do
    root to: 'pages#accueil'

    get '/biographie', to: 'pages#biographie'
    get '/musiques', to: 'pages#musiques'
    get '/mentions_legales', to: 'pages#mentions'
    get '/plan', to: 'pages#mapping'

    # 'destroy', 'index' n'existent pas.
    get '/devis/nouveau', to: 'devis#new', as: :devis_new
    resources :devis, except: %i[destroy index new]
    get '/devis/:id/envoi', to: 'devis#envoi_devis', as: :devis_envoi
    get '/devis/:id/pdf', to: 'devis#print_devis', as: :devis_pdf

    get '/contact', to: 'contacts#new', as: :new_contact
    post '/contact', to: 'contacts#create', as: :contacts
  end

  get '/admin', to: 'pages#admin', as: :admin

  authenticate :user do
    scope '/admin' do
      resource :devis_configurations
      get '/devis', to: 'admin_devis#index', as: :devis_index_admin
      get '/devis/:status', to: 'admin_devis#status', as: :devis_status_admin
      get '/devis/show/:id', to: 'admin_devis#show', as: :devis_show_admin
      get '/devis/change/:id/:status', to: 'admin_devis#change', as: :devis_update_admin
    end
  end

end

app/views/pages/accueil.html.erb
<html>
<head>
  <meta charset="UTF-8" />

  <title><%= titre %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Compositeur, musicien et artiste">
  <meta name="keywords" content="Geoffrey Turpin, compositeur, musicien, interprete, guitariste, jeux vidéos, Lyon">
  <meta property="og:site_name" content="Geoffrey Turpin" />
  <meta property="og:title" content="Geoffrey Turpin | Accueil" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="https://www.geoffreyturpin.fr/" />
  <meta property="og:image" content="http://geoffreyturpin.fr/img/guitare.jpg" />
  <meta property="og:description" content="Compositeur de musiques de films, jeux vidéos et pure" >
  <meta name="author" content="Joseph Levarato">
  <meta name="generator" content="Rubymine 2016.1">
  <meta name="geo.region" content="FR" />
  <meta name="geo.placename" content="Lyon" />

  <meta content="jd.levarato@gmail.com" name="dc.creator">
  <meta content="2016" name="dc.date">
  <%= stylesheet_link_tag 'bootstrap.min', 'style', media: 'all', 'data-turbolinks-track' => true %>
</head>
  <!-- Début body -->
<body>
  <div class="row landingpage">
    <div class="col-md-2 col-md-offset-8 landing-logo">
      <%= image_tag("logo")%>
    </div>
    <div class="col-md-offset-7 col-md-4">
        <div class="col-md-4 landing-button">
          <%= link_to(t('accueil.decouvre'), "/biographie")%>
        </div>
        <div class="col-md-offset-2 col-md-4 landing-button">
          <%= link_to(t('accueil.ecoute'), "/musiques")%>
        </div>
    </div>
  </div>
  <br clear="all" />

  <hr class="footer-start">
  <footer class="row footer">
    <div class="col-md-2 ">
      <p class="footer-address">06.72.44.40.45<br /> turpin-geoffrey@live.fr</p>
    </div>
    <div class="col-md-2 col-md-offset-6 footer-link">
      <%= link_to(t('layout.cgu'), '/mentions_legales')%>
    </div>
    <div class="col-md-1 footer-link">
      <%= link_to(t('layout.plansite'), "/plan")%>
    </div>
    <div class="col-md-1 footer-link">
      <% if I18n.locale == :en %>
          <%= link_to('Français', locale: :fr) %>

      <% else I18n.locale == :fr %>
          <%= link_to('English', locale: :en) %>
      <% end %>
    </div>
  </footer>

</body>
</html>

app/views/pages/admin.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h3 class="guf-title">Administration</h3>

    <div class="col-md-4">
      <h3>Suivi des devis</h3>
      <table class="table">
        <tbody>
        <tr>
          <td>Nouveaux devis</td>
          <td>
            <span class="badge">
              <%= @stat_devis[:pending] %>
            </span>
          </td>
          <td>
            <%= link_to 'Voir', devis_status_admin_path(status: 'pending') %></td>
        </tr>
        <tr>
          <td>Compositions en cours</td>
          <td>
            <span class="badge">
              <%= @stat_devis[:ongoing] %>
            </span>
          </td>
          <td><%= link_to 'Voir', devis_status_admin_path(status: 'ongoing') %></td>
        </tr>
        <tr>
          <td>Compositions terminées</td>
          <td>
            <span class="badge">
              <%= @stat_devis[:done] %>
            </span>
          </td>
          <td><%= link_to 'Voir', devis_status_admin_path(status: 'done') %></td>
        </tr>
        </tbody>
      </table>
      <div class="text-center">
        <%= link_to 'Tout voir', devis_status_admin_path(status: 'all'), class: 'form-button' %>
      </div>

    </div>

    <div class="col-md-4">
      <h3>Résumé des ratios</h3>
      <% if @ratios %>
        <table class="table">
          <tbody>
          <tr>
            <td>Facturation à la seconde (de base)</td>
            <td><%= number_to_currency(@ratios.ratio_facturation, unit: '€', format: '%n %u') %></td>
          </tr>
          <tr>
            <td>TVA</td>
            <td><%= @ratios.tva %> %</td>
          </tr>
          <tr>
            <td>Taux si composition à l'image</td>
            <td><%= number_to_currency(@ratios.taux_image, unit: '€', format: '%n %u') %></td>
          </tr>
          <tr>
            <td>taux si deadline</td>
            <td><%= number_to_currency(@ratios.deadline, unit: '€', format: '%n %u') %></td>
          </tr>
          <tr>
            <td>Multiplicateur par nouvelle musique</td>
            <td><%= number_to_currency(@ratios.per_new_music, unit: '€', format: '%n %u') %></td>
          </tr>
          <% @ratios.musics_ratios.each do |m| %>
              <tr>
                <td><b><%= m.music_genre %></b></td>
                <td><b><%= number_to_currency(m.ratio, unit: '€', format: '%n %u') %></b></td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <div class="text-center">
          <%= link_to 'Modifier', edit_devis_configurations_path, class: 'form-button' %>
        </div>

      <% else %>
        <div class="text-center">
          <h4>Aucun ratio enregistré pour le moment</h4>
          <%= link_to 'Nouveaux ratios', new_devis_configurations_path, class: 'form-button' %>
        </div>
      <% end %>
    </div>

    <div class="col-md-4">
      <h3>Simulation</h3>
      <div class="panel panel-default">
        <div class="panel-body">
          <% if @ratios %>
          <% @ratios.musics_ratios.each do |m| %>
            <% total = 210 * @ratios.ratio_facturation %>
            <% total *= m.ratio %>
            <% total = ((total / 100 ) * @ratios.tva ) + total %>

            <% total_deadline = total * @ratios.deadline %>
            <% total_image = total * @ratios.taux_image %>
            <% total_both = total_image * @ratios.deadline %>

            <p>Prix estimé pour une musique de <%= m.music_genre %> d'une durée de 3:30 :</p>

              <table class="table">
                <thead>
                  <tr>
                    <th>Prix</th>
                    <th>Prix <i class="fa fa-clock-o" aria-hidden="true"></i></th>
                    <th>Prix <i class="fa fa-picture-o" aria-hidden="true"></i></th>
                    <th>Prix <i class="fa fa-picture-o" aria-hidden="true"></i> + <i class="fa fa-clock-o" aria-hidden="true"></i></th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><%= number_to_currency(total, unit: '€', format: '%n %u') %></td>
                    <td><%= number_to_currency(total_deadline, unit: '€', format: '%n %u') %></td>
                    <td><%= number_to_currency(total_image, unit: '€', format: '%n %u') %></td>
                    <td><%= number_to_currency(total_both, unit: '€', format: '%n %u') %></td>
                  </tr>
                </tbody>
              </table>
          <% end %>
          <% else %>
            <div class="alert alert-danger">
              <p>Les ratios n'ont pas encore été définis</p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/biographie.html.erb
<div class="row biography">
  <div class="col-md-offset-2 col-md-4 biography-photo">
    <%= image_tag('biographie.jpg')%>
  </div>
  <div class="col-md-4 biography-text">
    <h3 class="guf-title">Geoffrey Turpin</h3>
    <p>
      <%= t('biographie.p1') %>
    </p>
    <p>
      <%= t('biographie.p2') %>
    </p>
    <p>
      <%= t('biographie.p3') %>
    </p>
  </div>
</div>
<div class="row parkour">
  <div class="col-md-offset-2 col-md-7 biography-chrono">
    <h3 class="guf-title"><%= t('biographie.parcours') %></h3>

    <div class="biography-year col-md-2 col-xs-4 col-md-offset-2">
      <p id="b2009">2009</p>
      <%=image_tag('chrono/year') %>
    </div>
    <div class="biography-year col-md-2 col-xs-4 col-md-offset-1">
      <p id="b2015">2015</p>
      <%=image_tag('chrono/year') %>
    </div>
    <div class="biography-year col-md-2 col-md-offset-2 col-xs-4">
      <p id="soon"><%= t('biographie.asuivre')%></p>
      <%=image_tag('chrono/year') %>
    </div>
    <br clear="all">

    <hr class="hr"/> <!-- ICI -->

    <div class="biography-raey col-md-2 col-xs-4">
      <%=image_tag('chrono/raey') %>
      <p id="b2003" class="detceles">2003</p>
    </div>

    <div class="biography-raey col-md-2 col-md-offset-1 col-xs-4">
      <%=image_tag('chrono/raey') %>
      <p id="b2011">2011</p>
    </div>

    <div class="biography-raey col-md-2 col-md-offset-2 col-xs-4">
      <%=image_tag('chrono/raey') %>
      <p id="b2016">2016</p>
    </div>

  </div>
  <!--<br clear="all">-->

  <div class="col-md-2 biography-desc">
    <h3>2003</h3>
    <ul>
      <li>Projection Privée, court métrage de Vincent Turpin</li>
    </ul>
  </div>
</div>

app/views/pages/mapping.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3 class="guf-title">Plan du site</h3>
    <ul>
      <li class="image-title">
        <%=link_to("Accueil", "/") %>
      </li>
      <li class="image-title">
        <%=link_to("Biographie", "/biographie") %>
      </li>
      <li class="image-title">
        <%=link_to("Musiques", "/musiques") %>
      </li>
      <li class="image-title">
        <%=link_to("Contact", "/contact") %>
      </li>
      <li class="image-title">
        <%=link_to("Mentions légales", "/mentions_legales") %>
      </li>
    </ul>
  </div>
  <div class="test">
    <%= t('hello') %>
  </div>
</div>

app/views/pages/mentions.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3 class="guf-title">Mentions legales</h3>

    <h4>MENTIONS LÉGALES DU SITE</h4>

    <p>de Geoffrey Turpin</p><br /><br />



    <p>Conformément aux dispositions des Articles 6-III et 19 de la Loi n°2004-575 du 21 juin 2004 pour la Confiance dans l'économie numérique, dite L.C.E.N., il est porté à la connaissance des
    utilisateurs et visiteurs du site de Geoffrey Turpin les présentes mentions légales. <br />


    Le site de Geoffrey Turpin est accessible à l'adresse suivante :<br /><br />
    http://www.geoffreyturpin.fr <br /><br />
    L'accès et l'utilisation du Site sont soumis aux présentes " Mentions légales" détaillées ci-après ainsi qu'aux lois et/ou règlements applicables.<br />
    <br />
    La connexion, l'utilisation et l'accès à ce Site impliquent l'acceptation intégrale et sans réserve de l'internaute de toutes les dispositions des présentes Mentions Légales.<br /><br />

    <b>ARTICLE 1 - INFORMATIONS LÉGALES</b><br /><br />

    En vertu de l'Article 6 de la Loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique, il est précisé dans cet article l'identité des différents intervenants dans le cadre de sa réalisation
    et de son suivi.<br /><br />

    Le site de Geoffrey Turpin est édité par Joseph Levarato domicilié à l'adresse suivante : <br /><br />
    17 Boulevard Yves Farges, et immatriculé au numéro suivant : 818 885 907 00019.<br /><br />

    Téléphone : 0675566262<br /><br />

    Adresse e-mail : jd.levarato@gmail.com<br /><br />



    Le Directeur de publication est :<br />

    Geoffrey Turpin.<br /><br />

    La directrice artistique est :<br />

    Sandra Campanale<br /><br />

    Adresse e-mail de contact : jd.levarato@gmail.com<br /><br />

    Le Directeur technique est :<br />

    Joseph Levarato<br /><br />


    Le site de Geoffrey Turpin est hébergé par OVH dont le siège est situé à l'adresse suivante : 2 Rue Kellermann, 59100 Roubaix<br />

    Téléphone : 09 72 10 10 07<br />

    Contact : https://www.ovh.com/fr/support/nous-contacter/.<br /><br />

    Sont considérés comme utilisateurs tout les internautes qui naviguent, lisent, visionnent et utilisent le site de Geoffrey Turpin.<br /><br />




    <b>ARTICLE 2 - ACCESSIBILITÉ</b><br /><br />

    Le Site est par principe accessible aux utilisateurs 24/24h et 7/7j, sauf interruption, programmée ou non, pour des besoins de maintenance ou en cas de force majeure.<br />

    En cas d'impossibilité d'accès au Site, celui-ci s'engage à faire son maximum afin d'en rétablir l'accès. Le Site ne saurait être tenu pour responsable de tout dommage,
    quelle qu'en soit la nature, résultant de son indisponibilité.<br /><br />


    <b>ARTICLE 3 - COLLECTE DE DONNÉES ET LOI INFORMATIQUE ET LIBERTÉS</b><br /><br />

    Le site de Geoffrey Turpin est exempté de déclaration à la Commission Nationale Informatique et Libertés (CNIL) dans la mesure où il ne collecte aucune donnée des Utilisateurs.<br /><br />

    <b>ARTICLE 5 - CONTACT</b><br /><br />

    Pour tout signalement de contenus ou d'activités illicites, l'Utilisateur peut contacter l'Éditeur à l'adresse suivante : jd.levarato@gmail.com, ou par courrier recommandé
    avec accusé de réception adressé à l'Éditeur aux coordonnées précisées dans les présentes mentions légales.<br /> <br />

    Crédits photo (page Biographie) : Margot Lombard<br />
    Crédits photo (page Accueil) : Sandra Campanale
    </p>
  </div>
</div>

app/views/pages/musiques.html.erb
<div class="col-md-10 col-md-offset-1">
<div id="carousel-example-generic" class="carousel slide">

  <div class="col-md-offset-2 col-md-3 col-xs-5 col-xs-offset-1 submenu-shown submenu" data-target="#carousel-example-generic" data-slide-to="0" id="compoimage">
    <p><%= t('musiques.compoimage')%></p>
  </div>
  <div class="col-md-offset-2 col-md-3 submenu col-xs-5 col-xs-offset-1" data-target="#carousel-example-generic" data-slide-to="1" id="compomusique">
    <p><%= t('musiques.musiquepure')%></p>
  </div>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <!-- Slide -->
    <div class="item active">
      <div class="row">
        <div class="col-md-12">
          <h3 class="guf-title"><%= t('musiques.compoimage')%></h3>
        </div>

        <div class="image-block">
          <div class="col-md-6 image-video">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/VSGFH0knUtI" frameborder="0" allowfullscreen></iframe>
          </div>
          <div class="col-md-6 image-desc">
            <p class="image-title">Sang d'Encre</p>
            <p class="image-author">Tom Gouill - Jeoffrey Lavanche - Mélanie Tournois- 2012</p>
            <p class="image-sbtitle">Musique symphonique et vocale</p>
            <div class="image-content"><%= t('musiques.desc3') %></div>
          </div>
        </div>

        <div class="image-block"> <!-- Copie-colle ça pour avoir le modèle de base à modifier ensuite-->
          <div class="col-md-6 image-video">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/ckHvf1YMUJM" frameborder="0" allowfullscreen></iframe>
          </div>
          <div class="col-md-6 image-desc">
            <p class="image-title">Démo fin 2015</p>
            <p class="image-author">Geoffrey Turpin - 11/2015</p>
            <p class="image-sbtitle"> </p>
            <div class="image-content"><%= t('musiques.desc1') %></div>
          </div>
        </div>

        <div class="image-block">
          <div class="col-md-6 image-video" style="margin-top: 17px">
            <iframe src="https://player.vimeo.com/video/164628449" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            <p>
          </div>
          <div class="col-md-6 image-desc">
            <p class="image-title">La Horde</p>
            <p class="image-author">Gamagora - 29/04/2016</p>
            <p class="image-sbtitle">Musique symphonique et vocale, sound design et intégration (Unreal Engine 4)</p>
            <div class="image-content"><%= simple_format(t('musiques.desc2')) %></div>
          </div>
        </div>

        <div class="image-block">
          <div class="col-md-6 image-video">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/nMIHsv72ld0" frameborder="0" allowfullscreen></iframe>
          </div>
          <div class="col-md-6 image-desc">
            <p class="image-title">Webimatics</p>
            <p class="image-author">Anaïs Gaudioz - 03/2016</p>
            <p class="image-sbtitle">Musique type "publicité" orchestral </p>
            <div class="image-content"><%= simple_format(t('musiques.desc4')) %></div>
          </div>
        </div>

        <div class="image-block">
          <div class="col-md-6 image-video">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/Hztl5DjjQ4c" frameborder="0" allowfullscreen></iframe>
          </div>
          <div class="col-md-6 image-desc">
            <p class="image-title">Web book</p>
            <p class="image-author">WCK Production - 04/2016</p>
            <p class="image-sbtitle">Musique électro / ambiant / experimental </p>
            <div class="image-content"><%= simple_format(t('musiques.desc5')) %></div>
          </div>
        </div>

        <div class="image-block">
          <div class="col-md-6 image-video">
            <iframe src="https://player.vimeo.com/video/132071923" width="640" height="315" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            <p>
              <a href="https://vimeo.com/132071923">TEASER JEU-VIDEO : Yohan Monange &quot;La Tombe du Typhon&quot;</a>
              de <a href="https://vimeo.com/cohl">Ecole Emile Cohl</a> on <a href="https://vimeo.com">Vimeo</a>.
            </p>
          </div>
          <div class="col-md-6 image-desc">
            <p class="image-title">La Tombe du Typhon</p>
            <p class="image-author">Yohan Monange - 03/2016</p>
            <p class="image-sbtitle">Musique symphonique, vocale et électronique et sound design </p>
            <div class="image-content"><%= simple_format(t('musiques.desc6')) %></div>
          </div>
        </div>
      </div>
    </div>
    <!-- Switch "musique pure" -->
    <div class="item">
      <div class="row">
        <div class="col-md-12">
          <h3 class="guf-title"><%= t('musiques.musiquepure')%></h3>
        </div>
        <div class="music-block">
          <div class="music-embed">
            <iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/172592426&amp;color=004703&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>
          </div>
          <div class="music-desc">
            <p>
              <%= t('musiques.desc7') %>
            </p>
          </div>
        </div>
          </div>
        </div>
      </div>
    </div>
  </div> <!--/#wrapper -->
<br clear="all" />