config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  scope '(:locale)', locale: /fr|en/ do
    root to: 'pages#accueil'

    get '/biographie', to: 'pages#biographie'
    get '/musiques', to: 'pages#musiques'
    get '/mentions_legales', to: 'pages#mentions'
    get '/plan', to: 'pages#mapping'

    # 'destroy', 'index' n'existent pas.
    get '/devis/nouveau', to: 'devis#new', as: :devis_new
    resources :devis, except: %i[destroy index new]
    get '/devis/:id/envoi', to: 'devis#envoi_devis', as: :devis_envoi
    get '/devis/:id/pdf', to: 'devis#print_devis', as: :devis_pdf

    get '/contact', to: 'contacts#new', as: :new_contact
    post '/contact', to: 'contacts#create', as: :contacts
  end

  get '/admin', to: 'pages#admin', as: :admin

  authenticate :user do
    scope '/admin' do
      resource :devis_configurations
      get '/devis', to: 'admin_devis#index', as: :devis_index_admin
      get '/devis/:status', to: 'admin_devis#status', as: :devis_status_admin
      get '/devis/show/:id', to: 'admin_devis#show', as: :devis_show_admin
      get '/devis/change/:id/:status', to: 'admin_devis#change', as: :devis_update_admin
    end
  end

end

app/models/devi.rb
class Devi < ApplicationRecord
  has_many :specs, inverse_of: :devi
  accepts_nested_attributes_for :specs, reject_if: :all_blank, allow_destroy: true
end

app/controllers/devis_controller.rb
class DevisController < ApplicationController
  before_action :set_devi, only: %i[show edit update destroy envoi_devis print_devis]

  def index
    @devis = Devi.all
  end

  def show
    if cookies[:session_id]
      @titre = 'Devis SGF-' + @devi.id.to_s
      @specs = Spec.find_by(devi_id: @devi.id)
      @ratios = DevisConfiguration.first
    else
      redirect_to new_devi_path, alert: 'Devis introuvable'
    end
  end

  def new
    @titre = 'Nouveau devis'
    @devi = Devi.new
    @devi.specs.build
    @musics = DevisConfiguration.first.musics_ratios.all if DevisConfiguration.exists?
  end

  def edit
    if cookies[:session_id]
      @specs = Spec.find_by(devi_id: @devi.id)
      @titre = 'Editer le devis SGF-' + @devi.id.to_s
    else
      redirect_to biographie_path, alert: "Vous ne pouvez plus modifier votre demande de devis ou vous n'avez pas le droit d'y accéder"
    end
    @musics = DevisConfiguration.first.musics_ratios.all
  end

  def create
    @devi = Devi.new(devi_params)

    respond_to do |format|

      @devi.price = set_price(devi_params)
      @devi.status = 'created'
      @devi.session_id = session.id

      if @devi.save

        cookies[:session_id] = { value: session.id, expires: 1.day.from_now }

        format.html { redirect_to @devi, notice: 'Devis créé avec succès' }
        format.json { render :show, status: :created, location: @devi }
      else
        format.html { render :new }
        format.json { render json: @devi.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @devi.update(devi_params)

        @devi.price = set_price(devi_params)

        format.html { redirect_to @devi, notice: 'Devis mis à jour' }
        format.json { render :show, status: :ok, location: @devi }
      else
        format.html { render :edit }
        format.json { render json: @devi.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @devi.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  def set_price(params)

    config = DevisConfiguration.first
    result = 0
    index = 0

    params[:specs_attributes].each do |_i, spec|
      # Calcul du coût de la musique par rapport à sa longueur
      taux_seconde = spec[:genre].partition('-').last * config.ratio_facturation.to_i
      result += (((spec[:minutes].to_i * 60).to_i + spec[:secondes].to_i).to_i * taux_seconde.to_i).to_i
      result *= config.taux_image if spec[:image].to_i == 1

      index += 1
    end

    # Calcul du coût par nouvelle musique s'il y en a plus d'une
    result *= config.per_new_music.to_i if index > 0
    # Calcul du bonus de deadline si elle a été définie
    result *= config.deadline unless params[:deadline].blank?

    # Ajout de la TVA
    tva = ((result / 100) * config.tva.to_i)

    price = [result, tva].to_json

    return price
  end

  def envoi_devis
    if cookies[:session_id] && @devi.status == 'created' ||
       cookies[:session_id] && @devi.status == 'pending'
      @titre = 'Devis envoyé'
      # unless @devi.status == 'created'
      ContactMailer.new_devis_notification(@devi).deliver
      @devi.update!(status: 'pending')
      # end

    else
      redirect_to biographie_path, alert: "Vous ne pouvez plus modifier votre demande de devis ou vous n'avez pas le droit d'y accéder"
    end
  end

  def print_devis
    @ratios = DevisConfiguration.first
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'print_devis',
               template: 'devis/print_devis.html.erb',
               disposition: 'attachment'
      end
    end
  end

  private

  def set_devi
    @devi = Devi.find(params[:id])
  end

  def devi_params
    params.require(:devi).permit(:nom, :prenom, :email, :status, :session_id, :currency, :deadline,
                                 specs_attributes: %i[id genre description image minutes secondes])
  end
end

app/helpers/devis_helper.rb
module DevisHelper
end

app/views/devis/_form.html.erb
<%= form_with(model: @devi, local: true) do |f| %>
    <fieldset>
      <div class="form-group col-md-12">
        <!--<label class="col-md-4 control-label" for="textinput">Text Input</label>-->
        <%= f.label :nom, class: 'col-md-4 control-label'%>
        <div class="col-md-4">
          <%= f.text_field :nom, placeholder: 'Nom', class: 'form-control input-md' %>
        </div>
      </div>

      <div class="form-group col-md-12">
        <%= f.label :prenom, class: 'col-md-4 control-label'%>
        <div class="col-md-4">
          <%= f.text_field :prenom, placeholder: 'Prénom', class: 'form-control input-md' %>
        </div>
      </div>

      <div class="form-group col-md-12">
        <%= f.label :email, 'Adresse e-mail', class: 'col-md-4 control-label'%>
        <div class="col-md-4">
          <%= f.text_field :email, placeholder: 'Adresse e-mail', class: 'form-control input-md' %>
        </div>
      </div>
    </fieldset>

    <br clear="all" />

  <div class="form-inputs">

    <hr class="hr-top"/>

    <div id="specs">
      <%= f.fields_for :specs do |spec| %>
        <%= render 'spec_fields', f: spec %>
      <% end %>
    </div>

    <div class="links col-md-4 col-md-offset-4 text-center">
      <%= link_to_add_association 'Ajouter une nouvelle musique ?', f, :specs, class: 'form-button' %>
    </div>

    <br clear="all" />

    <div class="form-group col-md-12">
      <%= f.label :currency, 'Choix de la devise', class: 'col-md-4 control-label'%>
      <div class="col-md-1">
        <%= f.select :currency, ['€', '$', 'CHF'], {}, { class: 'form-control' } %>
      </div>
    </div>

    <div class="form-group col-md-12">
      <%= f.label :deadline, 'Ajouter une deadline personnalisée ?', class: 'col-md-4 control-label' %>
      <div class="col-md-4">
        <div class="input-group">
          <span class="input-group-addon">
              <input type="checkbox" class="if-deadline">
          </span>
          <%= f.text_field :deadline,
                           'data-toggle' => 'datepicker',
                           class: 'datepicker form-control',
                           placeholder: 'ex: ' + Date.today.strftime('%d/%m/%Y'),
                           value: "#{f.object.deadline.strftime('%d/%m/%Y') if f.object.deadline unless f.object.new_record?}",
                           disabled: true
          %>
        </div>
      </div>
    </div>
  </div>

  <div class="form-actions col-md-offset-4 col-md-4">
    <%= link_to '← Retour', root_path, class: 'form-button' %>

    <%= f.submit 'Suivant →', class: 'form-button submit' %>
  </div>
<% end %>

app/views/devis/_spec_fields.html.erb
<div class="nested-fields">

  <div class="form-group">
    <div class="col-md-4 col-md-offset-4">
      <%= f.select :genre, @musics.collect{
          |m| [m.music_genre, m.music_genre + '-' + m.ratio.to_s]
      }, {prompt: 'Sélectionnez un type de musique'}, {class: 'form-control'}  %>
    </div>
  </div>

  <div class="form-group col-md-12 music-length">
    <%= f.label :minutes, 'Durée de la composition', class: 'col-md-4 control-label' %>
    <div class="col-md-4">
      <%= f.number_field :minutes, min: 0, max: 60, class: 'form-control input-md', placeholder: 'Minutes' %>
      <span>:</span>
      <%= f.number_field :secondes, min: 0, max: 60, class: 'form-control input-md', placeholder: 'Secondes' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :image, 'Composition à l\'image ?', class: 'col-md-4 control-label' %>
    <div class="col-md-4">
      <label class="switch">
        <%= f.check_box :image %>
        <span class="slider"></span>
      </label>
      <br clear="all" />
    </div>
  </div>

  <br clear="all" />

  <div class="form-group">
    <div class="col-md-4 col-md-offset-4">
      <%= f.text_area :description, placeholder: 'Donnez plus de détails', class: 'form-control' %>
    </div>
  </div>

  <div class="nested-action col-md-4 col-md-offset-4">
    <%= link_to_remove_association 'Supprimer', f, class: 'form-button' %>
  </div>

  <br clear="all" />

  <hr class="hr-top"/>
</div>

app/views/devis/edit.html.erb
<h1>Editing Devi</h1>

<%= render 'form', devi: @devi %>

<%= link_to 'Show', @devi %> |
<%= link_to 'Back', devis_path %>

app/views/devis/envoi_devis.html.erb
<h3 class="guf-title text-center">Envoi du devis avec succes</h3>

<h3 class="text-center">Votre devis a été envoyé à Geoffrey Turpin. </h3>
<p class="text-center">Geoffrey Turpin vous contactera prochainement afin que vous puissiez
vous mettre d'accord sur les termes du projet</p>

<br />

<div class="text-center">
  <%= link_to 'Imprimer le devis', devis_pdf_path(@devi.id, format: :pdf), class: 'form-button' %>
</div>

app/views/devis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Devis</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Email</th>
      <th>Telephone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devis.each do |devi| %>
      <tr>
        <td><%= devi.nom %></td>
        <td><%= devi.prenom %></td>
        <td><%= devi.email %></td>
        <td><%= devi.telephone %></td>
        <td><%= link_to 'Show', devi %></td>
        <td><%= link_to 'Edit', edit_devi_path(devi) %></td>
        <td><%= link_to 'Destroy', devi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Devi', new_devi_path %>

app/views/devis/new.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <% if @musics %>
    <h3 class="guf-title">Nouveau devis</h3>
    <%= render 'form', devi: @devi %>
    <% else %>
    <h1 class="text-center">Cette page est encore indisponible, veuillez revenir plus tard !</h1>
    <% end %>
  </div>
</div>

app/views/devis/print_devis.html.erb
<html>
<head>
  <meta charset="UTF-8" />
  <style>
    table {
      border-collapse: collapse;
    }

    table, th, td {
      border: 1px solid black;
    }

    .pull-right {
      float: right;
    }
  </style>
</head>
<body>
      <table class="table">
        <thead>
        <tr>
          <th>REFERENCE</th>
          <th>DATE</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>DEVIS-SGF-<%= @devi.id%></td>
          <td><%= @devi.updated_at.strftime('%d-%m-%Y') %></td>
        </tr>
        </tbody>
      </table>

    <table class="table">
      <thead>
        <tr>
          <th>Sélection</th>
          <th>Informations complémentaires</th>
          <th>Prix horst taxe</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
      <% @devi.specs.each do |spec| %>
          <tr>
            <td>
              <%= spec.genre.partition('-').first %> - Durée : <%= spec.minutes %>:<%= spec.secondes %>
              <% if spec.image %> - Composition à l'image <% end %>
              <% if @devi.deadline %>avec deadline définie (<%= @devi.deadline.strftime('%d/%m/%Y')%>) <% end %>
            </td>
            <td>
              <%= spec.description %>
            </td>
            <td>
              <% array = JSON::parse(@devi.price) %>
              <%= number_to_currency(array.first, unit: @devi.currency, format: '%n %u') %>
            </td>
            <td>
              <%= number_to_currency((array.first + array.last), unit: @devi.currency, format: '%n %u') %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <div class="pull-right">
      <table class="table">
        <thead>
        <tr>
          <th>Détail</th>
          <th>Ratio</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>Facturation à la seconde (de base)</td>
          <td><%= number_to_currency(@ratios.ratio_facturation, unit: @devi.currency, format: '%n %u')%></td>
        </tr>
        <tr>
          <td>TVA</td>
          <td><%= number_to_currency(@ratios.tva, unit: @devi.currency, format: '%n %u')%></td>
        </tr>
        <% if @devi.deadline %>
            <tr>
              <td>Deadline</td>
              <td><%= number_to_currency(@ratios.deadline, unit: @devi.currency, format: '%n %u')%></td>
            </tr>
        <% end %>
        <% image = false %>
        <% @devi.specs.each do |spec| %>
            <% if spec.image %>
                <% image = true %>
            <% end %>
        <% end %>

        <% if image %>
            <tr>
              <td>Composition à l'image</td>
              <td><%= number_to_currency(@ratios.taux_image, unit: @devi.currency, format: '%n %u')%></td>
            </tr>
        <% end %>

        <% if @devi.specs.length > 1 %>
            <tr>
              <td>Multiplicateur par nouvelle musique</td>
              <td><%= number_to_currency(@ratios.per_new_music, unit: @devi.currency, format: '%n %u')%></td>
            </tr>
        <% end %>

        </tbody>
      </table>
    </div>

</body>
</html>

app/views/devis/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <p>Vous pouvez encore modifier votre devis avant de le soumettre. Si toutefois vous décidez d'annuler la demande,
      vous ne pourrez pas la récupérer.</p>

    <div class="col-md-3">
      <table class="table">
        <thead>
        <tr>
          <th>REFERENCE</th>
          <th>DATE</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>DEVIS-SGF-<%= @devi.id%></td>
          <td><%= @devi.updated_at.strftime('%d-%m-%Y') %></td>
        </tr>
        </tbody>
      </table>
    </div>

    <table class="table">
      <thead>
      <tr>
        <th>Sélection</th>
        <th>Informations complémentaires</th>
        <th>Prix horst taxe</th>
        <th>Total</th>
      </tr>
      </thead>
      <tbody>
      <% @devi.specs.each do |spec| %>
          <tr>
            <td>
              <%= spec.genre.partition('-').first %> - Durée : <%= spec.minutes %>:<%= spec.secondes %>
              <% if spec.image %> - Composition à l'image <% end %>
              <% if @devi.deadline %>avec deadline définie (<%= @devi.deadline.strftime('%d/%m/%Y')%>) <% end %>
            </td>
            <td>
              <%= spec.description %>
            </td>
            <td>
              <% array = JSON::parse(@devi.price) %>
              <%= number_to_currency(array.first, unit: @devi.currency, format: '%n %u') %>
            </td>
            <td>
              <%= number_to_currency((array.first.to_i + array.last.to_i), unit: @devi.currency, format: '%n %u') %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <div class="col-md-3 pull-right">
      <table class="table">
        <thead>
        <tr>
          <th>Détail</th>
          <th>Ratio</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>Facturation à la seconde (de base)</td>
          <td><%= number_to_currency(@ratios.ratio_facturation, unit: @devi.currency, format: '%n %u')%></td>
        </tr>
        <tr>
          <td>TVA</td>
          <td><%= number_to_currency(@ratios.tva, unit: '%', format: '%n %u')%></td>
        </tr>
        <% if @devi.deadline %>
        <tr>
          <td>Deadline</td>
          <td><%= number_to_currency(@ratios.deadline, unit: @devi.currency, format: '%n %u')%></td>
        </tr>
        <% end %>
        <% image = false %>
        <% @devi.specs.each do |spec| %>
          <% if spec.image %>
            <% image = true %>
          <% end %>
        <% end %>

        <% if image %>
        <tr>
          <td>Composition à l'image</td>
          <td><%= number_to_currency(@ratios.taux_image, unit: @devi.currency, format: '%n %u')%></td>
        </tr>
        <% end %>

        <% if @devi.specs.length > 1 %>
          <tr>
            <td>Multiplicateur par nouvelle musique</td>
            <td><%= number_to_currency(@ratios.per_new_music, unit: @devi.currency, format: '%n %u')%></td>
          </tr>
        <% end %>

        </tbody>
      </table>
    </div>

    <br clear="all" />

    <div class="form-action text-center">
      <%= link_to '← Annuler', root_path, class: 'form-button' %>
      <%= link_to edit_devi_path(@devi), class: 'form-button' do %>
          <i class="fa fa-pencil" aria-hidden="true"></i>  Modifier le devis
      <% end %>

      <%= link_to 'Soumettre le devis →', devis_envoi_path(@devi.id), class: 'form-button' %>
    </div>
  </div>
</div>