config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  scope '(:locale)', locale: /fr|en/ do
    root to: 'pages#accueil'

    get '/biographie', to: 'pages#biographie'
    get '/musiques', to: 'pages#musiques'
    get '/mentions_legales', to: 'pages#mentions'
    get '/plan', to: 'pages#mapping'

    # 'destroy', 'index' n'existent pas.
    get '/devis/nouveau', to: 'devis#new', as: :devis_new
    resources :devis, except: %i[destroy index new]
    get '/devis/:id/envoi', to: 'devis#envoi_devis', as: :devis_envoi
    get '/devis/:id/pdf', to: 'devis#print_devis', as: :devis_pdf

    get '/contact', to: 'contacts#new', as: :new_contact
    post '/contact', to: 'contacts#create', as: :contacts
  end

  get '/admin', to: 'pages#admin', as: :admin

  authenticate :user do
    scope '/admin' do
      resource :devis_configurations
      get '/devis', to: 'admin_devis#index', as: :devis_index_admin
      get '/devis/:status', to: 'admin_devis#status', as: :devis_status_admin
      get '/devis/show/:id', to: 'admin_devis#show', as: :devis_show_admin
      get '/devis/change/:id/:status', to: 'admin_devis#change', as: :devis_update_admin
    end
  end

end

app/controllers/admin_devis_controller.rb
class AdminDevisController < ApplicationController
  def index
    @titre = 'Administration'
  end

  def status
    @titre = 'Liste des devis'
    status = params[:status]
    status == 'all' ? @devis = Devi.all : @devis = Devi.where(status: status)
  end

  def show
    @devis = Devi.find(params[:id])
    @titre = 'Devis SGF-' + @devis.id.to_s
  end

  def change
    @devis = Devi.find(params[:id])
    @devis.update!(status: params[:status])
    redirect_to devis_show_admin_path(@devis.id), notice: 'Composition définie comme "commencée"'
  end

  def destroy
    Devi.destroy(params[:id])
    redirect_to devis_status_admin_path(status: 'all'), notice: 'Devis supprimé avec succès'
  end
end

app/helpers/admin_devis_helper.rb
module AdminDevisHelper
end

app/views/admin_devis/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">

    <h3 class="guf-title">DEVIS-SGT-<%= @devis.id %></h3>

    <% status = @devis.status == 'pending' ? 'ongoing' : 'done' %>

    <div class="col-md-4">
      <table class="table">
        <thead>
        <tr>
          <th>REFERENCE</th>
          <th>DATE</th>
          <th>ÉTAT</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>DEVIS-SGF-<%= @devis.id%></td>
          <td><%= @devis.updated_at.strftime('%d/%m/%Y') %></td>
          <td>
            <% case @devis.status %>
              <% when 'pending' %>
                  <span class="label label-default">En attente</span>
              <% when 'ongoing' %>
                  <span class="label label-primary">En cours</span>
              <% when 'done' %>
                  <span class="label label-success">Terminé</span>
            <% end %>
          </td>
        </tr>
        </tbody>
      </table>
    </div>

    <table class="table">
      <thead>
      <tr>
        <th>Sélection</th>
        <th>Informations complémentaires</th>
        <th>Prix hors taxe</th>
        <th>Total</th>
      </tr>
      </thead>
      <tbody>
      <% @devis.specs.each do |spec| %>
          <tr>
            <td>
              <%= spec.genre.partition('-').first %> - Durée : <%= spec.minutes %>:<%= spec.secondes %>
              <% if spec.image %> - Composition à l'image <% end %>
              <% if @devis.deadline %>avec deadline définie (<%= @devis.deadline.strftime('%d/%m/%Y')%>) <% end %>
            </td>
            <td><%= spec.description %></td>
            <td>
              <% array = JSON::parse(@devis.price) %>
              <%= number_to_currency(array.first, unit: @devis.currency, format: '%n %u') %>
            </td>
            <td>
              <%= number_to_currency((array.first + array.last), unit: @devis.currency, format: '%n %u') %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br clear="all" />

    <div class="form-action text-center">

      <button onclick="location.href='/admin/devis/all'" class="form-button">
        ← Retour
      </button>

      <button type="button" class="form-button" data-toggle="modal" data-target="#delete">
        Supprimer le devis
      </button>

      <% unless @devis.status == 'done' %>
        <button type="button" class="form-button" data-toggle="modal" data-target="#update">
          <%= status == 'ongoing' ? 'Commencer le projet' : 'Terminer le projet' %>
        </button>
      <% end %>

    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="deleteLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="deleteLabel">Supprimer le devis ?</h4>
      </div>
      <div class="modal-body">
        Confirmer la suppression du devis SGT-<%= @devis.id %>
      </div>
      <div class="modal-footer">
        <button type="button" class="form-button active" data-dismiss="modal">Annuler</button>
        <button type="button" class="btn btn-primary">Supprimer</button>
      </div>
    </div>
  </div>
</div>

<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="update" tabindex="-1" role="dialog" aria-labelledby="updateLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="updateLabel">
          <%= @devis.status == 'pending' ? 'Commencer le projet ?' : 'Terminer le projet ?' %>
        </h4>
      </div>
      <div class="modal-body">
        Définir la composition SGT-<%= @devis.id %> comme étant
        <%= status == 'ongoing' ? 'commencé' : 'terminé' %> ?
      </div>

      <div class="modal-footer">
        <a href="#" class="form-button active" data-dismiss="modal">Annuler</a>
        <%= link_to 'Confirmer',
            devis_update_admin_path(id: @devis.id, status: status),
            class: 'form-button'
        %>
      </div>
    </div>
  </div>
</div>

app/views/admin_devis/status.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h3 class="guf-title">
      <% case params[:status] %>
        <% when 'pending' %>
            Projets en attente
        <% when 'ongoing' %>
            Projets en cours
        <% when 'done' %>
            Projets termines
        <% when 'all' %>
            Tous les projets
        <% else %>

      <% end %>
    </h3>

    <div class="text-center">
      <%= link_to 'En attente',
                  devis_status_admin_path('pending'),
                  class: current_page?(devis_status_admin_path('pending')) ?
                             'form-button active' : 'form-button'
      %>

      <%= link_to 'En cours',
                  devis_status_admin_path('ongoing'),
                  class: current_page?(devis_status_admin_path('ongoing')) ?
                             'form-button active' : 'form-button'
      %>

      <%= link_to 'Terminé',
                  devis_status_admin_path('done'),
                  class: current_page?(devis_status_admin_path('done')) ?
                             'form-button active' : 'form-button'
      %>

      <%= link_to 'Tout',
                  devis_status_admin_path('all'),
                  class: current_page?(devis_status_admin_path('all')) ?
                             'form-button active' : 'form-button'
      %>

    </div>

    <br />
    <br clear="all" />

    <table id="status" class="display" cellspacing="0" width="100%">
      <thead>
      <tr>
        <th>Nom</th>
        <th>Adresse e-mail</th>
        <th>Statut</th>
        <th>Prix estimé</th>
        <th>Deadline</th>
        <th>Date de création</th>
        <th></th>
      </tr>
      </thead>
      <tfoot>
      <tr>
        <th>Nom</th>
        <th>Adresse e-mail</th>
        <th>Statut</th>
        <th>Prix estimé</th>
        <th>Deadline</th>
        <th>Date de création</th>
        <th></th>
      </tr>
      </tfoot>
      <tbody>
      <% @devis.each do |devis| %>
          <tr>
            <td><%= devis.prenom %> <%= devis.nom %></td>
            <td><%= mail_to devis.email %></td>
            <td>
              <% case devis.status %>
                <% when 'pending' %>
                  <span class="label label-default">En attente</span>
                <% when 'ongoing' %>
                  <span class="label label-primary">En cours</span>
                <% when 'done' %>
                  <span class="label label-success">Terminé</span>
              <% end %>
            </td>
            <% array = JSON::parse(devis.price) %>
            <td><%= number_to_currency((array.first + array.last), unit: devis.currency, format: '%n %u TTC') %></td>
            <td><%= devis.deadline.nil? ? '- Aucune -' : devis.deadline.strftime('%d/%m/%Y') %></td>
            <td><%= devis.created_at.strftime('%d/%m/%Y')%></td>
            <td>
              <%= link_to 'Voir', devis_show_admin_path(devis.id) %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br clear="all" />

    <div class="text-center">
      <%= link_to '← Retour', admin_path, class: 'form-button' %>
    </div>
  </div>
</div>