config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  scope '(:locale)', locale: /fr|en/ do
    root to: 'pages#accueil'

    get '/biographie', to: 'pages#biographie'
    get '/musiques', to: 'pages#musiques'
    get '/mentions_legales', to: 'pages#mentions'
    get '/plan', to: 'pages#mapping'

    # 'destroy', 'index' n'existent pas.
    get '/devis/nouveau', to: 'devis#new', as: :devis_new
    resources :devis, except: %i[destroy index new]
    get '/devis/:id/envoi', to: 'devis#envoi_devis', as: :devis_envoi
    get '/devis/:id/pdf', to: 'devis#print_devis', as: :devis_pdf

    get '/contact', to: 'contacts#new', as: :new_contact
    post '/contact', to: 'contacts#create', as: :contacts
  end

  get '/admin', to: 'pages#admin', as: :admin

  authenticate :user do
    scope '/admin' do
      resource :devis_configurations
      get '/devis', to: 'admin_devis#index', as: :devis_index_admin
      get '/devis/:status', to: 'admin_devis#status', as: :devis_status_admin
      get '/devis/show/:id', to: 'admin_devis#show', as: :devis_show_admin
      get '/devis/change/:id/:status', to: 'admin_devis#change', as: :devis_update_admin
    end
  end

end

app/models/devis_configuration.rb
class DevisConfiguration < ApplicationRecord
  has_many :musics_ratios, inverse_of: :devis_configuration
  accepts_nested_attributes_for :musics_ratios, reject_if: :all_blank, allow_destroy: true
end

app/controllers/devis_configurations_controller.rb
class DevisConfigurationsController < ApplicationController
  before_action :set_devis_configuration, only: %i[show edit update destroy]

  # GET /devis_configurations
  # GET /devis_configurations.json
  def index
    @devis_configurations = DevisConfiguration.all
  end

  # GET /devis_configurations/1
  # GET /devis_configurations/1.json
  def show
  end

  # GET /devis_configurations/new
  def new
    @devis_configuration = DevisConfiguration.new
    @devis_configuration.musics_ratios.build
  end

  # GET /devis_configurations/1/edit
  def edit
    @devis_configuration = DevisConfiguration.find(1)
    @titre = 'Modification des taux du devis'
  end

  # POST /devis_configurations
  # POST /devis_configurations.json
  def create
    @devis_configuration = DevisConfiguration.new(devis_configuration_params)

    respond_to do |format|
      if @devis_configuration.save
        format.html { redirect_to admin_path, notice: 'Taux enregistrés avec succès' }
        format.json { render :show, status: :created, location: admin_path }
      else
        format.html { render :new }
        format.json { render json: @devis_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devis_configurations/1
  # PATCH/PUT /devis_configurations/1.json
  def update
    respond_to do |format|
      if @devis_configuration.update(devis_configuration_params)
        format.html { redirect_to admin_path, notice: 'Devis configuration was successfully updated.' }
        format.json { render :show, status: :ok, location: admin_path }
      else
        format.html { render :edit }
        format.json { render json: @devis_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devis_configurations/1
  # DELETE /devis_configurations/1.json
  def destroy
    @devis_configuration.destroy
    respond_to do |format|
      format.html { redirect_to devis_configurations_url, notice: 'Devis configuration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_devis_configuration
    @devis_configuration = DevisConfiguration.find(1)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def devis_configuration_params
    params.require(:devis_configuration).permit(:ratio_facturation, :tva, :taux_image, :deadline, :per_new_music,
                    musics_ratios_attributes: [:id, :music_genre, :ratio])
  end
end

app/helpers/devis_configurations_helper.rb
module DevisConfigurationsHelper
end

app/views/devis_configurations/_form.html.erb
<%= form_for(@devis_configuration, url: devis_configurations_path, html: {class: 'form-horizontal' }) do |f| %>
  <fieldset>

    <div class="form-group">
      <%= f.label :ratio_facturation, 'Prix de la musique à la seconde', class: 'col-md-4 control-label' %>
      <div class="col-md-4">
        <%= f.text_field :ratio_facturation, class: 'form-control input-md' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :tva, 'TVA', class: 'col-md-4 control-label' %>
      <div class="col-md-4">
        <%= f.text_field :tva, class: 'form-control input-md' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :taux_image, 'Taux pour composition à l\'image', class: 'col-md-4 control-label' %>
      <div class="col-md-4">
        <%= f.text_field :taux_image, class: 'form-control input-md' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :deadline, 'Bonus par nouvelle musique demandé', class: 'col-md-4 control-label' %>
      <div class="col-md-4">
        <%= f.text_field :deadline, class: 'form-control input-md' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :per_new_music, 'Bonus pour une musique supplémentaire', class: 'col-md-4 control-label' %>
      <div class="col-md-4">
        <%= f.text_field :per_new_music, class: 'form-control input-md' %>
      </div>
    </div>

    <div id="musics_ratios">
      <%= f.fields_for :musics_ratios do |music_ratio| %>
          <%= render 'musics_ratio_fields', f: music_ratio %>
      <% end %>
    </div>

    <br />
    <div class="links text-center">
      <%= link_to_add_association '+ Nouveau genre', f, :musics_ratios, class: 'form-button' %>
    </div>

    <div class="form-actions">
      <%= link_to '← Retour', admin_path, class: 'form-button' %>
      <%= f.submit 'Enregistrer', class: 'form-button' %>
    </div>

  </fieldset>

<% end %>

app/views/devis_configurations/_musics_ratio_fields.html.erb
<div class="nested-fields">

  <div class="form-group">
    <%= f.label :ratio, 'Taux pour la musique', class: 'col-md-3 control-label' %>
    <div class="col-md-1">
      <%= f.text_field :ratio, class: 'form-control input-md' %>
    </div>

    <%= f.label :music_genre, 'Type de la musique', class: 'col-md-2 control-label' %>
    <div class="col-md-2">
      <%= f.text_field :music_genre, class: 'form-control input-md' %>
    </div>

    <%= link_to_remove_association '– Supprimer', f, class: 'form-button' %>
  </div>
</div>

app/views/devis_configurations/edit.html.erb
<div class="col-md-offset-2 col-md-8">
  <h1>Modification des taux du devis</h1>
  <%= render 'form', devis_configuration: @devis_configurations %>
</div>
<br clear="all" />

app/views/devis_configurations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Devis Configurations</h1>

<table>
  <thead>
    <tr>
      <th>Ratio facturation</th>
      <th>Tva</th>
      <th>Taux image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devis_configurations.each do |devis_configuration| %>
      <tr>
        <td><%= devis_configuration.ratio_facturation %></td>
        <td><%= devis_configuration.tva %></td>
        <td><%= devis_configuration.taux_image %></td>
        <td><%= link_to 'Show', devis_configuration %></td>
        <td><%= link_to 'Edit', edit_devis_configuration_path(devis_configuration) %></td>
        <td><%= link_to 'Destroy', devis_configuration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Devis Configuration', new_devis_configuration_path %>

app/views/devis_configurations/new.html.erb
<div class="col-md-offset-2 col-md-8">
  <h1>Configuration du devis</h1>
  <%= render 'form', devis_configuration: @devis_configuration %>
</div>
<br clear="all" />

app/views/devis_configurations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ratio facturation:</strong>
  <%= @devis_configuration.ratio_facturation %>
</p>

<p>
  <strong>Tva:</strong>
  <%= @devis_configuration.tva %>
</p>

<p>
  <strong>Taux image:</strong>
  <%= @devis_configuration.taux_image %>
</p>

<%= link_to 'Edit', edit_devis_configuration_path(@devis_configuration) %> |
<%= link_to 'Back', devis_configurations_path %>